export const USER_NEW_PICTURE = "USER_NEW_PICTURE";
export const SET_USER_PICTURES = "SET_USER_PICTURES";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const SET_PAGINATION_END= "SET_PAGINATION_END";
export const DELETE_PICTURE = "DELETE_PICTURE";